### ISSUE TITLE
ERROR: Write to InfluxDB failed. d [HttpError]: 204 HTTP response status code expected, but 200 returned

### ISSUE THREAD

**Issue by drewdrewthis** [influxdata/influxdb-client-js#372]
__Expected Behavior:__

`writeApi` methods should return a 204 (according to documentation). Tried `writeRecord` and `writePoint`.

__Current Behavior:__

`writeApi` method returning a 200 and producing the following error:

```
ERROR: Write to InfluxDB failed. d [HttpError]: 204 HTTP response status code expected, but 200 returned
    at [object Object] (/var/service/node_modules/@influxdata/influxdb-client/src/impl/WriteApiImpl.ts:198:29)
    at IncomingMessage.complete (/var/service/node_modules/@influxdata/influxdb-client/src/impl/completeCommunicationObserver.ts:30:43)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  statusCode: 200,
  statusMessage: '204 HTTP response status code expected, but 200 returned',
  body: undefined,
  contentType: undefined,
  _retryAfter: 0
}
```

__Possible Solution:__

Investigate why client isn't passing data correctly to POST.

The following works directly with http in the same system

```
axios.post(
  'http://influxdb:8086/api/v2/write?org=dex&bucket=bucket1&precision=ns',
  'airSensors,sometag="hot" valueField=169',
  {
    headers: {
      Authorization:  'Token oz1GqcTy9Cqau2ktWJCNvNzdD8BYJvuSqKi5joQU74zVJufIa9_IvLZALzAm5KMsV7qO4FJ7YgSrRRCaHvNOxw==',
      'Content-Type': 'text/plain; charset=utf-8',
    },
  },
)
```

__Steps/Code to Reproduce the Problem:__

1. step1 - docker-compose file
```
version: '3.8'

volumes:
  data:
    external: false

services:
  influxdb:
    image: 'influxdb'
    volumes:
      # Mount for influxdb data directory
      - ./.influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./.influxdb/config/:/etc/influxdb/
      # Mount for influxdb logs
      - ./.influxdb/logs/:/var/log/influxdb/
      # Mount for v2 everything
      - ./.influxdb/testdata:/root/.influxdbv2
    ports:
      # The API for InfluxDB is served on port 8086
      - '8086:8086'
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
```

Client details:
```
 "timeout": 10000,
    "url": "http://influxdb::8086",
    "token": "oz1GqcTy9Cqau2ktWJCNvNzdD8BYJvuSqKi5joQU74zVJufIa9_IvLZALzAm5KMsV7qO4FJ7YgSrRRCaHvNOxw==",
    "transportOptions": {},
    "port": "8086",
    "protocol": "http:",
    "hostname": "influxdb"
 ```

Step 2 (From example):
```
import { InfluxDB, Point, HttpError } from '@influxdata/influxdb-client';
import logger from '@dex-arbitrage/logger';
import axios from 'axios';

const { hostname } = require('os');

const host = process.env.INFLUX_HOST;
const token = process.env.INFLUX_ADMIN_TOKEN;
const org = process.env.INFLUX_ORG;
const bucket = process.env.INFLUX_BUCKET;

logger.info(`Influx Host: ${host}`);
logger.info(`Influx Token: ${token}`);
logger.info(`Influx org: ${org}`);
logger.info(`Influx bucket: ${bucket}`);

if (!host) throw new ReferenceError('INFLUX_HOST is undefined');
if (!org) throw new ReferenceError('INFLUX_ORG is undefined');
if (!bucket) throw new ReferenceError('INFLUX_BUCKET is undefined');

console.log('*** WRITE POINTS ***');
// create a write API, expecting point timestamps in nanoseconds (can be also 's', 'ms', 'us')
const writeApi = new InfluxDB({ url: host, token }).getWriteApi(org, bucket, 'ns');
// setup default tags for all writes through this API
writeApi.useDefaultTags({ location: hostname() });

// write point with the current (client-side) timestamp
const point1 = new Point('temperature')
  .tag('example', 'write.ts')
  .floatField('value', 20 + Math.round(100 * Math.random()) / 10);
writeApi.writePoint(point1);
console.log(` ${point1}`);
// write point with a custom timestamp
const point2 = new Point('temperature')
  .tag('example', 'write.ts')
  .floatField('value', 10 + Math.round(100 * Math.random()) / 10)
// can be also a number, but in writeApi's precision units (s, ms, us, ns)!
  .timestamp(new Date());

writeApi.writePoint(point2);
console.log(` ${point2.toLineProtocol(writeApi)}`);

// WriteApi always buffer data into batches to optimize data transfer to InfluxDB server and retries
// writing upon server/network failure. writeApi.flush() can be called to flush the buffered data,
// close() also flushes the remaining buffered data and then cancels pending retries.
writeApi
  .close()
  .then(() => {
    console.log('FINISHED ... now try ./query.ts');
  })
  .catch((e) => {
    console.error(e);
    if (e instanceof HttpError && e.statusCode === 401) {
      console.log('Run ./onboarding.js to setup a new InfluxDB database.');
    }
    console.log('\nFinished ERROR');
  });
```

__Specifications:__

- Version: 
```
"@influxdata/influxdb-client@^1.10.0":
  resolved "https://registry.yarnpkg.com/@influxdata/influxdb-client/-/influxdb-client-1.18.0.tgz#e86d75b063d4c23ad094fb5dfa3b243731fe149a"
```
InfluxDB 2.0.9

- Platform: MacOS M1 Running Docker
